List<String> moralStory = [
  "Once upon a time, in a small village nestled between lush green hills, there lived a wise old farmer named Ramu. Ramu was known throughout the village for his kindness, honesty, and unwavering optimism.",
  "One summer, a severe drought struck the village, leaving the fields barren and the villagers worried about their livelihoods. Despite the challenging times, Ramu remained hopeful and continued tending to his crops diligently, believing that the rains would eventually come.",
  "As the days passed without any sign of rain, the other farmers grew increasingly desperate. Some of them resorted to dishonesty, stealing water from their neighbors' wells in a bid to save their own crops. However, Ramu refused to follow suit, firmly believing that honesty was the best policy.",
  "One day, a weary traveler passing through the village stopped by Ramu's farm, seeking shelter from the scorching sun. Ramu welcomed the traveler with open arms, offering him food and water despite the scarcity of resources.",
  "Impressed by Ramu's kindness, the traveler revealed himself to be a wandering sage blessed with the power to bring rain. He explained that he had been testing the villagers' integrity and generosity, and Ramu was the only one who had passed with flying colors.",
  "Touched by Ramu's honesty and compassion, the sage performed a sacred ritual, and soon dark clouds gathered in the sky. The parched earth soaked up the long-awaited rain, reviving the wilted crops and bringing new life to the village.",
  "From that day onward, the villagers learned an invaluable lesson from Ramu's example. They realized that honesty, kindness, and perseverance were the true keys to prosperity, and they lived harmoniously, sharing whatever little they had with each other.",
  "And so, the village thrived not only because of the rain that nourished the land but also because of the moral values that guided its people, inspired by the wisdom of the humble farmer, Ramu."
];
